Updated test runner.

diff --git a/tests/run b/tests/run
--- a/tests/run
+++ b/tests/run
@@ -1,11 +1,8 @@
 #! /bin/bash
 ###############################################################################
 #                                                                             #
-#                                  Alice                                      #
-#                                                                             #
-#                             Tests Run Script                                #
-#                                                                             #
-#                       Copyright (C) 2012-, AdaHeads K/S                     #
+#                     Copyright (C) 2012-2013, AdaHeads K/S                   #
+#       Copyright (C) 2013-, Jacob Sparre Andersen Research & Innovation      #
 #                                                                             #
 #  This is free software;  you can redistribute it  and/or modify it          #
 #  under terms of the  GNU General Public License as published  by the        #
@@ -47,9 +44,10 @@ for file in $(find ./ -mindepth 2 -type f -perm +100 | sort); do
 
    echo ${run_number}/${number_of_runs}$'\tRunning '${file}' for at most '${allowed_time_in_seconds}' seconds...' 1>&2
 
-   ./${file} $(cat ${file}.arguments) 1>${file}.output \
-                                      2>${file}.errors \
-                                      &
+   tr '\n' '\0' < ${file}.arguments \
+     | xargs --null ./${file} 1>${file}.output \
+                              2>${file}.errors \
+                              &
    pid=$!
 
    (
@@ -72,6 +70,20 @@ for file in $(find ./ -mindepth 2 -type f -perm +100 | sort); do
       echo ${run_number}/${number_of_runs}$'\tRun succeeded.' 1>&2
 
       echo "${file}"             >> ${succeeded_list}
+
+      rm -f ${file}.{output,errors}
+   elif [ ${result} -eq 123 ]; then
+      echo ${run_number}/${number_of_runs}$'\tRun was terminated by an exception.' 1>&2
+
+      echo "${file} (exception)" >>    ${failed_list}
+   elif [ ${result} -eq 137 ]; then
+      echo ${run_number}/${number_of_runs}$'\tRun was terminated by SIGKILL.' 1>&2
+
+      echo "${file} (SIGKILL)"   >>    ${failed_list}
+   elif [ ${result} -eq 143 ]; then
+      echo ${run_number}/${number_of_runs}$'\tRun was terminated by SIGTERM.' 1>&2
+
+      echo "${file} (SIGTERM)"   >>    ${failed_list}
    else
       echo ${run_number}/${number_of_runs}$'\tRun failed with exit code '${result}'.' 1>&2
 
@@ -85,7 +97,7 @@ failed=$(cat ${failed_list} | wc -l)
 
 if [ -s ${failed_list} ]; then
    echo "${failed} out of ${total} tests failed:"
-   uniq < ${failed_list} | sed 's|^|  |'
+   uniq < ${failed_list} | sed 's|^.|   tests|'
 else
    echo "All ${total} tests succeeded."
 fi
